name: Bot Tweet

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  tweet:
    name: tweet
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
    - run: go run main.go
      env:
        TWITTER_CLIENT_ID: ${{secrets.TWITTER_CLIENT_ID}}
        TWITTER_CLIENT_SECRET: ${{secrets.TWITTER_CLIENT_SECRET}}
        TWITTER_REFRESH_TOKEN: ${{secrets.TWITTER_REFRESH_TOKEN}}
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}