name: Bot Tweet

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  tweet:
    name: tweet
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '>=1.18'
    - run: go run main.go
      env:
        TWITTER_CLIENT_ID: ${{ secrets.TWITTER_CLIENT_ID }}
        TWITTER_CLIENT_SECRET: ${{ secrets.TWITTER_CLIENT_SECRET }}
        TWITTER_REFRESH_TOKEN: ${{ secrets.TWITTER_REFRESH_TOKEN }}
      continue-on-error: true
    - uses: hmanzur/actions-set-secret@v2.0.0
      with:
        name: TWITTER_REFRESH_TOKEN
        value: ${{ steps.tweet.outputs.refresh_token }}
        token: ${{ secrets.TOKEN_GITHUB }}

        secret: true
      if: ${{ steps.tweet.outputs.refresh_token }}